dist: trusty
sudo: required
language: php

php:
- '7.1'
- '7.2'
- '7.3'
- '7.4'

before_script:
- composer self-update
- composer update

script:
- COMPOSER=composer PHP=php make phpunit

after_script:
- make clean

branches:
  only:
  - master
  - '/^ft-.*/'
  - '/^\d+\.\d+\.\d+$/'

cache:
  directories:
  - $HOME/.composer/cache/files
